CREATE DATABASE if NOT EXISTS todo;

USE todo;

CREATE TABLE if NOT EXISTS endereco
	(id INT AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	endereco VARCHAR(100) NOT NULL)


CREATE TABLE if NOT EXISTS tarefa